### ISSUE TITLE
Last update showing incorrectly

### ISSUE THREAD

**Issue by GawainLynch** [bolt/site-market-bolt-cm#12]
![screenshot from 2015-08-21 10-06-28](https://cloud.githubusercontent.com/assets/1427081/9405140/1d0452de-47ed-11e5-99a7-af3ecca9dba0.png)

**Comment by Mikescops** [comment]
You serious gawain ?? The database in not running ^^ Look my last extension is not here !

**Comment by GawainLynch** [comment]
Yes, I am serious… Look at the screen shot:

v2.4.0 Released 18th August 2015
Last Update: 13th Nov 2014

Database updates are irrelevant

**Comment by Mikescops** [comment]
Last update at the top is stored in the database and updated when you click on update. Well i think so.

Changelog is using Github API.

**Comment by GawainLynch** [comment]
OK, sure… but from a UX point-of-view it is confusing. As a user, what information am I supposed to rely on?

**Comment by Mikescops** [comment]
May I say, "last stable version" ?

**Comment by Mikescops** [comment]
"last published version" ?

**Comment by GawainLynch** [comment]
Long since fixed
