### ISSUE TITLE
Cannot register an account

### ISSUE THREAD

**Issue by mikemcgowan** [bolt/site-market-bolt-cm#68]
I get the following:
![bolt-marketplace-cannot-register](https://cloud.githubusercontent.com/assets/2492670/26207714/38627bf8-3be0-11e7-859f-c05d6ebfd8fb.png)

**Comment by GawainLynch** [comment]
Yep, turned out to be a derpy database change that I made with the wrong user … created an account for myself just now!

Humble apologies for the delay :smiley_cat:
