### ISSUE TITLE
Can't view and update extensions when logged in

### ISSUE THREAD

**Issue by xiaohutai** [bolt/site-market-bolt-cm#69]
When logged in:
- Clicking on update an extension, I get the Bolt back-end login form.
- Clicking on view an extension, I get a "Whoops, looks like something went wrong.":

![whoops](https://cloud.githubusercontent.com/assets/4630335/26350707/8c10e2e4-3fb4-11e7-8117-f5c5283979ce.png)

**Comment by GawainLynch** [comment]
This one is now fixed … I hadn't pulled in some changes to production that I had sent to @SahAssar for something else … :koala:
