### ISSUE TITLE
Update button redirects to /bolt/login

### ISSUE THREAD

**Issue by SahAssar** [bolt/site-market-bolt-cm#72]
When clicking the update button on the package list to force a update of a package I am redirected to the bolt login page. No package update seems to be done.

The requested url is `https://market.bolt.cm/bolt/extensions/update?package=e1310b36-fc83-41b7-b0aa-569a34bcf040` and the response is a 302 Found with `Location:/bolt/login`.

Browser: Chrome 59.0.3071.86

**Comment by GawainLynch** [comment]
I'll try and dig into this tomorrow, mate … but don't let this hang too long … if I forget, give me a nudge in Slack.

**Comment by GawainLynch** [comment]
Welp, this one literally just opened a can of worms … as one particular extension needed an update. Fixes incoming, left & right.

**Comment by GawainLynch** [comment]
OK, fixed and deployed … and a tonne of clean up while I was there
