### ISSUE TITLE
Copy to clipboard not working

### ISSUE THREAD

**Issue by lenvanessen** [bolt/site-market-bolt-cm#73]
extension-extras.js?10c575006f:8 Uncaught ReferenceError: ZeroClipboard is not defined
    at HTMLDocument.<anonymous> (extension-extras.js?10c575006f:8)
    at i (jquery.min.js:2)
    at Object.add [as done] (jquery.min.js:2)
    at n.fn.init.n.fn.ready (jquery.min.js:2)
    at extension-extras.js?10c575006f:1

**Comment by GawainLynch** [comment]
Again :disappointed: 

Noting here that last time it was the CDN b0rking

**Comment by GawainLynch** [comment]
Fixed with https://github.com/bolt/marketplace-theme/commit/760d680063dcad3c8bdb4de9492774c21ec252c6

Short version is the ZeroClipboard project seems to be DOA, and being Flash based … well :wink:
