### ISSUE TITLE
Can´t register: PODException

### ISSUE THREAD

**Issue by develth** [bolt/site-market-bolt-cm#75]
Hi, 

i hit "Sign in with GitHub", gave all perms & added then username, mail & password. After Submit i got this Error:

![bildschirmfoto 2018-01-31 um 19 46 27](https://user-images.githubusercontent.com/3374563/35641128-969d6be2-06bf-11e8-85a2-a49532c8ab68.png)

**Comment by GawainLynch** [comment]
Argh! That's back :disappointed: 

Thanks, @develth I'll look into it in the morning.

**Comment by GawainLynch** [comment]
OK, decided to have a go at fixing this before bed … should be good now.

**Comment by develth** [comment]
i´ve tried to register with two almost similar mails, with all came this error but when i try to register ist says that the mail is already in use. What shall i do?

**Comment by GawainLynch** [comment]
Oh, I removed the "in process" registrations for you last night … I might have messed up, let me look.

**Comment by develth** [comment]
My mistake, works!

Is it ok that just a blank (just header & footer) page appears after providing the data?

**Comment by GawainLynch** [comment]
Yep, just found it and saw the tick appear next to "verified".

OK, I'll close this off then. Feel free to reopen if need be.
